### ISSUE TITLE
Fix the code

### ISSUE THREAD

**Issue by MButcho** [noderators/elastos-supernode-setup#1]
sudo dpkg -i --force-confmiss elastos-ela_0.4.3-1.deb elastos-did_0.1.4-1.deb elastos-token_0.1.2-2.deb elastos-carrier-bootstrap_5.2.3-2.deb elastos-metrics_1.2.0-2.deb ioex-mainchain_0.2.1-1.deb;

replace elastos-token_0.1.2-2.deb to elastos-token_0.1.2-3.deb

**Comment by kpachhai** [comment]
Thanks. Fixed
